require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/model_providers", type: :request do
  
  # ModelProvider. As you add validations to ModelProvider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ModelProvider.create! valid_attributes
      get model_providers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      model_provider = ModelProvider.create! valid_attributes
      get model_provider_url(model_provider)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_model_provider_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      model_provider = ModelProvider.create! valid_attributes
      get edit_model_provider_url(model_provider)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ModelProvider" do
        expect {
          post model_providers_url, params: { model_provider: valid_attributes }
        }.to change(ModelProvider, :count).by(1)
      end

      it "redirects to the created model_provider" do
        post model_providers_url, params: { model_provider: valid_attributes }
        expect(response).to redirect_to(model_provider_url(ModelProvider.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ModelProvider" do
        expect {
          post model_providers_url, params: { model_provider: invalid_attributes }
        }.to change(ModelProvider, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post model_providers_url, params: { model_provider: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested model_provider" do
        model_provider = ModelProvider.create! valid_attributes
        patch model_provider_url(model_provider), params: { model_provider: new_attributes }
        model_provider.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the model_provider" do
        model_provider = ModelProvider.create! valid_attributes
        patch model_provider_url(model_provider), params: { model_provider: new_attributes }
        model_provider.reload
        expect(response).to redirect_to(model_provider_url(model_provider))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        model_provider = ModelProvider.create! valid_attributes
        patch model_provider_url(model_provider), params: { model_provider: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested model_provider" do
      model_provider = ModelProvider.create! valid_attributes
      expect {
        delete model_provider_url(model_provider)
      }.to change(ModelProvider, :count).by(-1)
    end

    it "redirects to the model_providers list" do
      model_provider = ModelProvider.create! valid_attributes
      delete model_provider_url(model_provider)
      expect(response).to redirect_to(model_providers_url)
    end
  end
end
